### ISSUE TITLE
Structure spacing offset not applied correctly

### ISSUE THREAD

**Issue by Gbergz** [BarionLP/DungeonsEnhanced#5]
Right now structures of different types can spawn ontop of each other and super close to each other making them not that rare even if seperate spacing and rarity is turned up.

**Images**: 
![image](https://user-images.githubusercontent.com/26634554/150038037-36eb249d-0b98-4438-b14e-92d871a50cab.png)
![2022-01-19_01 00 30](https://user-images.githubusercontent.com/26634554/150038208-c05d9204-ca6b-4450-91b4-b0237333387d.png)

**-** Gbergz

**Comment by BarionLP** [comment]
With the 1.3 update every problem related to this should be fixed. this seems more like a bug to me. Can you provide more information (MC version, Forge version, Mod version, in case other mods you have installed)?

**Comment by Gbergz** [comment]
MC: 1.18.1
Forge: 39.0.36
DungeonsEnhanced: 3.0b1 on CF | filename: dungeons_enhanced-1.18.1-3.0-BETA | https://www.curseforge.com/minecraft/mc-mods/dungeonsenhanced/files/3608281
Modpack is Limitless 5, but I've not added the mod yet. But the modlist is basically the same as this version: (Scrolldown)
https://www.curseforge.com/minecraft/modpacks/tnp-limitless-5/files/3607080

**Comment by Gbergz** [comment]
No rush, just wondering if this new update will be out today or another day. Gonna publish an update to Limitless 5 and pondering on whether I should include this version of the mod since the placement of the structures are weird atm.

**Comment by BarionLP** [comment]
Guess you have to wait until a stable version of Dungeons Enhanced is out before you can include it. Anyway thanks for wanting to include us.

**Comment by Matthysse** [comment]
Can confirm,
![2022-01-20_11 52 09](https://user-images.githubusercontent.com/32510957/150350856-331c8169-75b7-464f-99b3-a46385d1785a.png)
![2022-01-20_11 58 30](https://user-images.githubusercontent.com/32510957/150350867-3a9bd193-752f-4b14-8b3f-12428a0bd28d.png)
![2022-01-19_14 30 07](https://user-images.githubusercontent.com/32510957/150350886-3d5dbc92-e3fb-403c-b84e-676475a120c5.png)
Espacially the last one, the structures should verify if they are underground, because here it's reaaaaaally weird x)
Some structures should spawn columns of cobblestone (like the woodland mansion in vanilla) when generating, like the castle etc., so they don't float or float with an island under them.

**Comment by BarionLP** [comment]
thanks for your images! this is not related to this issue (sorry for the unclear title). You don't have to create a new one, most of the problems you showed are already fixed in the next Update

**Comment by BarionLP** [comment]
Try updating Structure Gel. They fixed a few issues that could affect this issue.

**Comment by Gbergz** [comment]
> Try updating Structure Gel. They fixed a few issues that could affect this issue.

Will do.

**Comment by Gbergz** [comment]
Seems to be working better. (I think atleast). Although structure placement seems a bit rough.
![image](https://user-images.githubusercontent.com/26634554/151678508-6cef9c49-2682-4c72-ac14-897832e1a7fd.png)

**Comment by BarionLP** [comment]
yea, wait for the next update. It should fix most of the placement issues

**Comment by BarionLP** [comment]
update is out. It fixes almost everthing in this issue.

**Comment by BarionLP** [comment]
I'll create a new issue with the remaining issues

**Comment by Gbergz** [comment]
Update on this. Spacing between each structure seems to be an issue still. got 5 structures spawning super close to eachother. Like ontop aswell.
![image](https://user-images.githubusercontent.com/26634554/152649435-b4dbebd3-8ce3-4d4f-a57f-f08161b381b3.png)

A Tower of the Undead, Ruined Building, Stables, Pillager Camp & a Druid Circle.

### Versions:
Minecraft: 1.18.1
Forge: 39.0.64
Dungeons Enchanced: 3.0b2 | https://www.curseforge.com/minecraft/mc-mods/dungeonsenhanced/files/3633941
Structure Gel API: 2.1.3 | https://www.curseforge.com/minecraft/mc-mods/structure-gel-api/files/3629303

**Comment by BarionLP** [comment]
yes, I heard it a few times now. I guess I know what went wrong but I hadn't enought time to fix it. Hope I manage to solve it in the next days.

**Comment by BarionLP** [comment]
hopefully fixed in the next beta

**Comment by Armokthespideroverlord** [comment]
It looks like this issue is still persisting as of the latest update in one last way, and that's how dungeon overlap now only seems to happen at world spawn, sometimes with other modded dungeons and vanilla ones too:
![2022-02-19_04 07 53](https://user-images.githubusercontent.com/30275515/154794603-18182be5-688c-4c8d-8606-3791a35f9d3c.png)
![2022-02-19_04 09 54](https://user-images.githubusercontent.com/30275515/154794604-ece19e56-20f0-4f5e-ae5a-f0cf806cb326.png)
![2022-02-19_04 12 25](https://user-images.githubusercontent.com/30275515/154794605-3f238402-7223-4b59-a32e-679c7368f09e.png)
 (they also sometimes don't overlap and just mean you get a nice set of dungeons to loot pretty much immediately at spawn, which is kinda nice if you ask me, but usually you get some mess like seen above)

I've also noticed that the ice pit dungeon seems to generate much deeper than it should, or at least noticed that happen once:
![2022-02-19_03 56 58](https://user-images.githubusercontent.com/30275515/154794663-b5515a17-505d-4850-8412-433245f4e9ba.png)

in any case, it's good to see that I otherwise won't be experiencing dungeon overlap as I had back in 1.16 versions of this mod, so cheers to that at least!

**Comment by Armokthespideroverlord** [comment]
scratch that, it looks like overlap can still happen occasionally outside of spawn:
![2022-02-19_04 07 53](https://user-images.githubusercontent.com/30275515/154834927-bfa2cd34-be6d-45b4-8f33-d67053f105e7.png)

**Comment by BarionLP** [comment]
it'll be fixed in beta 3, which hasn't yet been released

**Comment by BarionLP** [comment]
next beta is out, hopefully it's now fixed

**Comment by Matthysse** [comment]
Sorry to say, but does not seem to be fixed:
![2022-02-23_19 21 46](https://user-images.githubusercontent.com/32510957/155385439-20d04b2f-416d-40bd-90b7-b0cc4eeed7b8.png)
And there are sometime still weird rough borders:
![2022-02-23_19 21 46](https://user-images.githubusercontent.com/32510957/155385631-c49339cb-35b5-4fc9-a288-fea10a1acd52.png)

**Comment by BarionLP** [comment]
have you deleted you config? I'm pretty sure that the spreading is fixed.
If not please give me seed and coords 

yea, the borders are the next problem I have to fix

**Comment by Matthysse** [comment]
Yes, removed the config and seems to work fine now, thanks!
